kind: pipeline
name: run_tests

steps:
  - name: testing
    image: cypress/browsers:chrome69
    commands:
      - npm ci
      - npx cypress run --browser chrome --spec cypress/integration/unidosh/**/*
trigger:
  branch:
    - master
    - stable*